# -*- coding: latin-1 -*-
"""A worked line of real Clarion for every public member of every class.

The build FAILS if a member has none, so the manual cannot fall behind the
code: add a method and the build tells you the manual is missing an example.
Keys are "Class.Member".  `Mailer` is the global EmailToClass object the
emailTo template declares.
"""

EXAMPLES = {

# =====================================================================
#  EmailNetClass  -  the transport primitives
# =====================================================================
'EmailNetClass.Conn':          "IF Mailer.Net.Conn THEN Mailer.Net.Close().        ! non-zero while a socket is open",
'EmailNetClass.Secure':        "IF NOT Mailer.Net.Secure THEN MESSAGE('This connection is NOT encrypted').",
'EmailNetClass.LastError':     "IF Mailer.Net.LastError = ETNet:Timeout THEN Mailer.Net.Timeout = 60000.",
'EmailNetClass.LastWinError':  "MESSAGE('TLS refused, Windows code ' & Mailer.Net.LastWinError)   ! 590624 = client cert asked for",
'EmailNetClass.LastErrorText': "MESSAGE(CLIP(Mailer.Net.LastErrorText))            ! 'The TLS handshake failed'",
'EmailNetClass.Timeout':       "Mailer.Net.Timeout = 60000                         ! milliseconds; 30000 by default",
'EmailNetClass.VerifyCert':    "Mailer.Net.VerifyCert = 0                          ! ONLY for a self-signed server on your own LAN",
'EmailNetClass.Trace':         "Mailer.Net.Trace = 1                               ! record the conversation in TraceQ",
'EmailNetClass.HidePasswords': "Mailer.Net.HidePasswords = 0                       ! show credentials in the log - never on a customer machine",
'EmailNetClass.Response':      "IF Mailer.Net.RespLen THEN Loc:Body = Mailer.Net.Response[1 : Mailer.Net.RespLen].",
'EmailNetClass.RespLen':       "MESSAGE('The service answered with ' & Mailer.Net.RespLen & ' bytes')",
'EmailNetClass.RespCap':       "MESSAGE('The response buffer currently holds ' & Mailer.Net.RespCap & ' bytes')",
'EmailNetClass.Status':        "IF Mailer.Net.Status = 401 THEN MESSAGE('The API key was rejected').",
'EmailNetClass.BinLen':        "Loc:Sealed = Mailer.Net.Protect('secret'); Loc:Len = Mailer.Net.BinLen",
'EmailNetClass.TraceQ':        "LOOP i = 1 TO RECORDS(Mailer.Net.TraceQ); GET(Mailer.Net.TraceQ, i); Loc:Line = Mailer.Net.TraceQ.Line; END",

'EmailNetClass.Construct':     "Net  EmailNetClass                                 ! Construct runs here, before your CODE",
'EmailNetClass.Destruct':      "!  runs at program end: closes the socket and frees the credential handles",
'EmailNetClass.Open':          "IF NOT Mailer.Net.Open('smtp.gmail.com', 465, 1) THEN MESSAGE(Mailer.Net.LastErrorText).",
'EmailNetClass.StartTls':      "IF NOT Mailer.Net.StartTls('smtp.gmail.com') THEN MESSAGE('TLS upgrade refused').",
'EmailNetClass.Send':          "Mailer.Net.Send('MAIL FROM:<sales@acme.com><13,10>')",
'EmailNetClass.SendLine':      "Mailer.Net.SendLine('AUTH LOGIN ' & Loc:Blob, 1)   ! 1 = a credential, masked in the log",
'EmailNetClass.RecvLine':      "Loc:Reply = Mailer.Net.RecvLine()                  ! '250 2.1.0 Ok', without the CRLF",
'EmailNetClass.Close':         "Mailer.Net.Close()                                 ! polite TLS shutdown, then the socket",
'EmailNetClass.IsOpen':        "IF Mailer.Net.IsOpen() THEN Mailer.Net.SendLine('QUIT').",
'EmailNetClass.Http':          "Loc:Status = Mailer.Net.Http('POST', 'https://api.resend.com/emails', Loc:Hdrs, Loc:Json)",
'EmailNetClass.Body':          "Loc:Reason = Mailer.OAuth.JsonValue(Mailer.Net.Body(), 'message')",
'EmailNetClass.OAuthListen':   "Loc:Id = Mailer.Net.OAuthListen(0, Loc:Port)       ! 0 = let Windows pick a free port",
'EmailNetClass.OAuthWait':     "Loc:Query = Mailer.Net.OAuthWait(Loc:Id, 180, Loc:Html)   ! 'code=4/0Ab...&state=xyz'",
'EmailNetClass.OAuthStop':     "Mailer.Net.OAuthStop(Loc:Id)                       ! always, even after a timeout",
'EmailNetClass.OpenUrl':       "Mailer.Net.OpenUrl('https://accounts.google.com/o/oauth2/v2/auth?...')",
'EmailNetClass.Sha256':        "Loc:Digest = Mailer.Net.Sha256(Loc:Verifier)       ! 32 raw bytes; BinLen is 32",
'EmailNetClass.RandomBytes':   "Loc:Verifier = Mailer.Msg.Base64Url(Mailer.Net.RandomBytes(32))",
'EmailNetClass.Protect':       "Loc:Sealed = Mailer.Net.Protect('my-app-password') ! DPAPI, this Windows user only",
'EmailNetClass.Unprotect':     "Loc:Clear = Mailer.Net.Unprotect(Loc:Sealed[1 : Loc:SealedLen])",
'EmailNetClass.SetErr':        "Mailer.Net.SetErr(ETNet:Timeout)                   ! from a derived class of your own",
'EmailNetClass.AddTrace':      "Mailer.Net.AddTrace('--- retrying with the backup server')",
'EmailNetClass.ClearTrace':    "Mailer.Net.ClearTrace()                            ! before a send, so the log is just this one",
'EmailNetClass.TraceText':     "Loc:Log = Mailer.Net.TraceText()                   ! the whole transcript, CRLF separated",

# =====================================================================
#  EmailBufClass  -  the growing byte buffer
# =====================================================================
'EmailBufClass.Buf':           "Loc:First = Mailer.Msg.Mime.Buf[1 : 100]           ! never read past .Len",
'EmailBufClass.Len':           "MESSAGE('The message is ' & Mailer.Msg.Mime.Len & ' bytes')",
'EmailBufClass.Cap':           "MESSAGE('Capacity ' & Mailer.Msg.Mime.Cap & ', used ' & Mailer.Msg.Mime.Len)",

'EmailBufClass.Construct':     "Buf  EmailBufClass                                 ! starts at 1 KB and doubles",
'EmailBufClass.Destruct':      "!  runs at scope end and releases the buffer",
'EmailBufClass.Need':          "Mailer.Msg.Mime.Need(2000000)                      ! pre-size before a known-big append",
'EmailBufClass.Add':           "Mailer.Msg.TextBody.Add('One more line.')",
'EmailBufClass.AddLen':        "Mailer.Msg.TextBody.AddLen(Loc:Raw, Loc:RawLen)    ! binary-safe: takes the length",
'EmailBufClass.AddLine':       "Mailer.Msg.TextBody.AddLine('Regards,')            ! appends CRLF for you",
'EmailBufClass.ClearAll':      "Mailer.Msg.TextBody.ClearAll()                     ! NOT Clear - that name breaks CLEAR()",
'EmailBufClass.Value':         "Loc:Body = Mailer.Msg.TextBody.Value()",

# =====================================================================
#  EmailMsgClass  -  the message and its MIME
# =====================================================================
'EmailMsgClass.FromAddr':      "Mailer.Msg.FromAddr = 'sales@acme.com'             ! or let the account fill it in",
'EmailMsgClass.FromName':      "Mailer.Msg.FromName = 'Acme Sales'",
'EmailMsgClass.ReplyTo':       "Mailer.Msg.ReplyTo = 'support@acme.com'",
'EmailMsgClass.Subject':       "Mailer.Msg.Subject = 'Factura N<250>mero 42'                ! accents are handled for you",
'EmailMsgClass.Priority':      "Mailer.Msg.Priority = ETPri:High                   ! X-Priority: 1 + Importance: High",
'EmailMsgClass.CharSet':       "Mailer.Msg.CharSet = ETChs:Ansi                    ! send the raw bytes as windows-1252",
'EmailMsgClass.ReadReceipt':   "Mailer.Msg.ReadReceipt = 1                         ! adds Disposition-Notification-To",
'EmailMsgClass.BccInHeaders':  "Mailer.Msg.BccInHeaders = 1                        ! Send() sets this per transport for you",
'EmailMsgClass.OwnMessageId':  "Mailer.Msg.OwnMessageId = 0                        ! let the provider assign the Message-ID",
'EmailMsgClass.MessageId':     "Mailer.Msg.MessageId = '<' & Loc:Guid & '@acme.com>'   ! blank = generated for you",
'EmailMsgClass.TzMinutes':     "Mailer.Msg.TzMinutes = -300                        ! force the Date: offset; 0 = ask Windows",
'EmailMsgClass.AddrQ':         "LOOP i = 1 TO RECORDS(Mailer.Msg.AddrQ); GET(Mailer.Msg.AddrQ, i); Loc:To = Mailer.Msg.AddrQ.Address; END",
'EmailMsgClass.AttachQ':       "MESSAGE(RECORDS(Mailer.Msg.AttachQ) & ' file(s) attached')",
'EmailMsgClass.HeaderQ':       "MESSAGE(RECORDS(Mailer.Msg.HeaderQ) & ' extra header(s)')",
'EmailMsgClass.TextBody':      "Mailer.Msg.TextBody.Add('Appended after SetText.')",
'EmailMsgClass.HtmlBody':      "IF Mailer.Msg.HtmlBody.Len THEN Loc:IsHtml = 1.",
'EmailMsgClass.Mime':          "Loc:Size = Mailer.Msg.Mime.Len                     ! valid once Build() has run",
'EmailMsgClass.LastError':     "IF Mailer.Msg.LastError = ETMsg:AttachMissing THEN MESSAGE('That file is gone').",
'EmailMsgClass.LastErrorText': "MESSAGE(CLIP(Mailer.Msg.LastErrorText))",
'EmailMsgClass.MaxSize':       "Mailer.Msg.MaxSize = 20000000                      ! refuse to build past 20 MB",

'EmailMsgClass.Construct':     "Msg  EmailMsgClass                                 ! Construct allocates the buffers",
'EmailMsgClass.Destruct':      "!  runs at scope end: frees every buffer and every in-memory attachment",
'EmailMsgClass.ClearAll':      "Mailer.Msg.ClearAll()                              ! start a fresh message",
'EmailMsgClass.SetFrom':       "Mailer.Msg.SetFrom('sales@acme.com', 'Acme Sales')",
'EmailMsgClass.SetSubject':    "Mailer.Msg.SetSubject('Your invoice')",
'EmailMsgClass.AddTo':         "Mailer.Msg.AddTo('bob@example.com', 'Bob Smith')",
'EmailMsgClass.AddCc':         "Mailer.Msg.AddCc('accounts@acme.com')",
'EmailMsgClass.AddBcc':        "Mailer.Msg.AddBcc('archive@acme.com')              ! goes in RCPT TO, never in a header",
'EmailMsgClass.AddList':       "Mailer.Msg.AddList('a@x.com; b@y.com, c@z.com', ETAddr:To)",
'EmailMsgClass.SetText':       "Mailer.Msg.SetText('The invoice is attached.')",
'EmailMsgClass.AddText':       "Mailer.Msg.AddText('<13,10>Thank you for your order.')",
'EmailMsgClass.SetHtml':       "Mailer.Msg.SetHtml('<p>The invoice is <b>attached</b>.</p>')",
'EmailMsgClass.AddHtml':       "Mailer.Msg.AddHtml('<p>Reply to this message with any question.</p>')",
'EmailMsgClass.Attach':        "IF NOT Mailer.Msg.Attach('C:\\inv\\INV-1042.pdf') THEN MESSAGE(Mailer.Msg.LastErrorText).",
'EmailMsgClass.AttachData':    "Mailer.Msg.AttachData('report.csv', Loc:Csv, 'text/csv')",
'EmailMsgClass.AttachInline':  "Mailer.Msg.AttachInline('logo.png', 'logo')        ! then <img src=\"cid:logo\"> in the HTML",
'EmailMsgClass.AddHeader':     "Mailer.Msg.AddHeader('X-Order-Id', Ord:Number)",
'EmailMsgClass.Validate':      "IF NOT Mailer.Msg.Validate() THEN MESSAGE(Mailer.Msg.LastErrorText).",
'EmailMsgClass.Build':         "IF Mailer.Msg.Build() < 0 THEN MESSAGE(Mailer.Msg.LastErrorText).",
'EmailMsgClass.RecipientList': "Loc:Shown = Mailer.Msg.RecipientList(ETAddr:To)    ! 'Bob Smith <bob@example.com>'",
'EmailMsgClass.EnvelopeCount': "LOOP i = 1 TO Mailer.Msg.EnvelopeCount(); Loc:One = Mailer.Msg.EnvelopeAddr(i); END",
'EmailMsgClass.EnvelopeAddr':  "Loc:Rcpt = Mailer.Msg.EnvelopeAddr(1)              ! To, Cc and Bcc, in order",
'EmailMsgClass.Base64':        "Loc:B64 = Mailer.Msg.Base64('Man')                 ! 'TWFu'",
'EmailMsgClass.Base64Len':     "Mailer.Msg.Base64Len(Loc:Raw, Loc:RawLen, Mailer.Msg.Mime)   ! 76-column lines",
'EmailMsgClass.Base64Decode':  "Loc:Raw = Mailer.Msg.Base64Decode('TWFu')          ! 'Man'",
'EmailMsgClass.Base64Url':     "Loc:Chal = Mailer.Msg.Base64Url(Loc:Digest)        ! -_ and no padding, for PKCE",
'EmailMsgClass.QuotedPrintable': "Loc:Qp = Mailer.Msg.QuotedPrintable(Loc:Utf8)    ! 'caf=C3=A9'",
'EmailMsgClass.Utf8':          "Loc:Utf8 = Mailer.Msg.Utf8('Direcci<243>n')                ! Windows-1252 in, UTF-8 out",
'EmailMsgClass.EncodeHeader':  "Loc:Hdr = Mailer.Msg.EncodeHeader('Factura N<250>mero')     ! '=?UTF-8?B?...?='",
'EmailMsgClass.NeedsEncoding': "IF Mailer.Msg.NeedsEncoding(Cus:Name) THEN Loc:Name = Mailer.Msg.EncodeHeader(Cus:Name).",
'EmailMsgClass.BodyNeedsQp':   "IF Mailer.Msg.BodyNeedsQp(Mailer.Msg.TextBody) THEN Loc:Enc = 'quoted-printable'.",
'EmailMsgClass.Boundary':      "Loc:Bound = Mailer.Msg.Boundary()                  ! '----=_emailTo_294294197354795'",
'EmailMsgClass.DateHeader':    "Loc:Date = Mailer.Msg.DateHeader()                 ! 'Sat, 22 Aug 2026 14:04:33 -0600'",
'EmailMsgClass.GuessType':     "Loc:Type = Mailer.Msg.GuessType('invoice.pdf')     ! 'application/pdf'",
'EmailMsgClass.JsonString':    "Loc:Json = '{{\"subject\":' & Mailer.Msg.JsonString(Ord:Subject) & '}'",
'EmailMsgClass.SetErr':        "Mailer.Msg.SetErr(ETMsg:TooBig, 'That attachment is over our limit.')",
'EmailMsgClass.LoadFile':      "IF Mailer.Msg.LoadFile('C:\\inv\\INV-1042.pdf', Loc:Buf) THEN Loc:Size = Loc:Buf.Len.",

# =====================================================================
#  EmailOAuthClass  -  the sign-in
# =====================================================================
'EmailOAuthClass.Net':           "Mailer.OAuth.Net.Timeout = 60000                 ! borrowed from EmailToClass, not owned",
'EmailOAuthClass.Msg':           "Loc:B64 = Mailer.OAuth.Msg.Base64Url(Loc:Raw)    ! the borrowed encoder object",
'EmailOAuthClass.LastError':     "IF Mailer.OAuth.LastError = ETSend:Consent THEN MESSAGE('Sign-in was cancelled').",
'EmailOAuthClass.LastErrorText': "MESSAGE(CLIP(Mailer.OAuth.LastErrorText))",
'EmailOAuthClass.AuthUrl':       "MESSAGE('Consent screen: ' & CLIP(Mailer.OAuth.AuthUrl))",
'EmailOAuthClass.TokenUrl':      "MESSAGE('Token endpoint: ' & CLIP(Mailer.OAuth.TokenUrl))",
'EmailOAuthClass.RedirectPort':  "Mailer.OAuth.RedirectPort = 8721                 ! pin it when a firewall rule needs one port",
'EmailOAuthClass.RedirectHost':  "Mailer.OAuth.RedirectHost = 'localhost'          ! blank = 127.0.0.1 for Google, localhost for Microsoft",
'EmailOAuthClass.LastAuthUrl':   "MESSAGE(CLIP(Mailer.OAuth.LastAuthUrl))          ! paste it into a browser to see what the provider objects to",
'EmailOAuthClass.WaitSeconds':   "Mailer.OAuth.WaitSeconds = 300                   ! five minutes to finish signing in",

'EmailOAuthClass.Init':          "Mailer.OAuth.Init(Mailer.Net, Mailer.Msg)        ! EmailToClass.Construct already did this",
'EmailOAuthClass.SetEndpoints':  "Mailer.OAuth.SetEndpoints(Mailer.Acc)            ! fills AuthUrl and TokenUrl from the provider",
'EmailOAuthClass.RedirectUri':   "Loc:Uri = Mailer.OAuth.RedirectUri(Mailer.Acc, 51234)     ! 'http://127.0.0.1:51234'",
'EmailOAuthClass.BuildAuthUrl':  "Loc:Url = Mailer.OAuth.BuildAuthUrl(Mailer.Acc, Loc:Port, Loc:Challenge, Loc:State)",
'EmailOAuthClass.Authorize':     "IF NOT Mailer.OAuth.Authorize(Mailer.Acc) THEN MESSAGE(Mailer.OAuth.LastErrorText).",
'EmailOAuthClass.Refresh':       "IF NOT Mailer.OAuth.Refresh(Mailer.Acc) THEN Mailer.OAuth.Authorize(Mailer.Acc).",
'EmailOAuthClass.EnsureToken':   "IF NOT Mailer.OAuth.EnsureToken(Mailer.Acc) THEN RETURN.   ! refreshes only if it must",
'EmailOAuthClass.DefaultScope':  "MESSAGE('Asking for: ' & Mailer.OAuth.DefaultScope(Mailer.Acc))",
'EmailOAuthClass.XOAuth2Blob':   "Loc:Blob = Mailer.OAuth.XOAuth2Blob(Mailer.Acc.UserName, Mailer.Acc.AccessToken)",
'EmailOAuthClass.JsonValue':     "Loc:Tok = Mailer.OAuth.JsonValue(Mailer.Net.Body(), 'access_token')",
'EmailOAuthClass.UrlEncode':     "Loc:Enc = Mailer.OAuth.UrlEncode('a b+c')        ! 'a%20b%2Bc'",
'EmailOAuthClass.UrlDecode':     "Loc:Raw = Mailer.OAuth.UrlDecode('a%20b')        ! 'a b'",
'EmailOAuthClass.QueryValue':    "Loc:Code = Mailer.OAuth.QueryValue(Loc:Query, 'code')",
'EmailOAuthClass.SetErr':        "Mailer.OAuth.SetErr(ETSend:Token, 'The tenant refused this application.')",

# =====================================================================
#  EmailToClass  -  the sender
# =====================================================================
'EmailToClass.Acc':             "Mailer.Acc.Host = 'smtp.office365.com'            ! the whole account lives here",
'EmailToClass.Net':             "Mailer.Net.Trace = 1                              ! the transport it owns",
'EmailToClass.OAuth':           "Mailer.OAuth.WaitSeconds = 300",
'EmailToClass.Msg':             "Mailer.Msg.AddTo('bob@example.com')               ! the message SendSimple and Compose use",
'EmailToClass.Language':        "Mailer.Language = ETLng:Spanish                   ! every window and message switches",
'EmailToClass.Silent':          "Mailer.Silent = 1                                 ! never pop a message box; check LastErrorText",
'EmailToClass.Trace':           "Mailer.Trace = 1                                  ! keep the conversation for the Log tab",
'EmailToClass.IniFile':         "Mailer.IniFile = PATH() & '\\mail.ini'             ! the default store, when no table is mapped",
'EmailToClass.IniSection':      "Mailer.IniSection = 'Mail'                        ! section prefix inside that INI",
'EmailToClass.LastError':       "IF Mailer.LastError = ETSend:Auth THEN MESSAGE('Check the password').",
'EmailToClass.LastErrorText':   "MESSAGE(CLIP(Mailer.LastErrorText))               ! always says why",
'EmailToClass.LastServerReply': "MESSAGE('The server said: ' & CLIP(Mailer.LastServerReply))",
'EmailToClass.Capabilities':    "IF INSTRING('XOAUTH2', Mailer.Capabilities, 1, 1) THEN Mailer.Acc.AuthMode = ETAuth:XOAuth2.",

'EmailToClass.Construct':       "Mailer  EmailToClass                              ! builds Net, Msg, OAuth and the buffers",
'EmailToClass.Destruct':        "!  runs at program end: closes any socket and frees everything it built",
'EmailToClass.Init':            "Mailer.Init(PATH() & '\\emailTo.ini')",
'EmailToClass.SetProvider':     "Mailer.SetProvider(ETPrv:Gmail)                   ! host, port, security and sign-in in one call",
'EmailToClass.ProviderName':    "MESSAGE('Sending through ' & Mailer.ProviderName(Mailer.Acc.Provider))",
'EmailToClass.ApiUrl':         "Mailer.Acc.ApiBase = 'http://127.0.0.1:8098'",
'EmailToClass.AccountQ':       "GET(Mailer.AccountQ, 2)                           ! .Name .Provider .ProviderText .FromAddr",
'EmailToClass.ListAccounts':   "IF Mailer.ListAccounts() > 1 THEN DO PickOne.     ! VIRTUAL - the template walks your table",
'EmailToClass.DeleteAccount':  "Mailer.DeleteAccount('brevo')                     ! the unnamed default cannot be deleted",
'EmailToClass.RememberAccount': "Mailer.RememberAccount('sendgrid')                  ! come back up on this one",
'EmailToClass.PreferredAccount': "Mailer.LoadAccount(Mailer.PreferredAccount('default'))  ! last chosen, else this",
'EmailToClass.LoadAccount':     "Mailer.LoadAccount('billing')                     ! VIRTUAL - the template points it at your table",
'EmailToClass.SaveAccount':     "Mailer.SaveAccount()                              ! VIRTUAL - what the Setup window calls on Save",
'EmailToClass.Seal':            "Set:Password = Mailer.Seal(Loc:Typed)             ! DPAPI + base64, safe for a text column",
'EmailToClass.Unseal':          "Mailer.Acc.Password = Mailer.Unseal(Set:Password)",
'EmailToClass.Send':            "IF NOT Mailer.Send(Mailer.Msg) THEN Mailer.ShowError().",
'EmailToClass.SendSimple':      "IF NOT Mailer.SendSimple('bob@acme.com','Invoice','It is attached.','INV.pdf') THEN Mailer.ShowError().",
'EmailToClass.TestAccount':     "IF Mailer.TestAccount() THEN MESSAGE('The account works').   ! sends nothing to anybody",
'EmailToClass.SendSmtp':        "Mailer.SendSmtp(Mailer.Msg)                       ! VIRTUAL - override to log every send",
'EmailToClass.SendGmailApi':    "Mailer.Acc.Transport = ETTrn:GmailApi; Mailer.Send(Mailer.Msg)",
'EmailToClass.SendGraphApi':    "Mailer.Acc.Transport = ETTrn:GraphApi; Mailer.Send(Mailer.Msg)",
'EmailToClass.SendApiKey':      "Mailer.Acc.Transport = ETTrn:ApiKey; Mailer.Send(Mailer.Msg)",
'EmailToClass.Authorize':       "IF NOT Mailer.Authorize() THEN MESSAGE(Mailer.LastErrorText).   ! opens the browser",
'EmailToClass.Setup':           "IF Mailer.Setup() THEN Mailer.LoadAccount().      ! the account window; 1 = saved",
'EmailToClass.Compose':         "Mailer.Compose(Cus:Email, 'Your statement', '', Loc:PdfName)",
'EmailToClass.ShowError':       "Mailer.ShowError()                                ! respects Silent; does nothing on success",
'EmailToClass.Txt':             "?SendBtn{PROP:Text} = Mailer.Txt(ETTxt:Send)      ! override Txt to add a third language",
'EmailToClass.SetErr':          "Mailer.SetErr(ETSend:NoAccount, 'No mailbox is configured for this branch.')",
'EmailToClass.EhloDomain':      "MESSAGE('We announce ourselves as ' & Mailer.EhloDomain())",
'EmailToClass.Expect':          "IF NOT Mailer.Expect('250,251') THEN MESSAGE(Mailer.LastServerReply).",
'EmailToClass.SmtpCmd':         "IF NOT Mailer.SmtpCmd('NOOP', '250') THEN MESSAGE('The server stopped answering').",
'EmailToClass.DotStuff':        "Mailer.DotStuff(Mailer.Msg)                       ! doubles a leading '.' on every line",
'EmailToClass.JsonRecipients':  "Loc:To = Mailer.JsonRecipients(Mailer.Msg, ETAddr:To, 'sg')   ! [{\"email\":\"bob@x.com\"}]",

# =====================================================================
#  EmailJsonClass  -  reading what a provider sends back
# =====================================================================
'EmailJsonClass.NodeQ':        "GET(MailApi.Json.NodeQ, 1); Loc:Kind = MailApi.Json.NodeQ.Kind   ! the parsed document, in order",
'EmailJsonClass.Doc':          "Loc:First = MailApi.Json.Doc[1 : 1]                ! the reply, exactly as it arrived",
'EmailJsonClass.DocLen':       "MESSAGE('The provider sent ' & MailApi.Json.DocLen & ' bytes')",
'EmailJsonClass.LastError':    "IF MailApi.Json.LastError = ETJs:Syntax THEN MESSAGE('That was not JSON').",
'EmailJsonClass.LastErrorText':"MESSAGE(CLIP(MailApi.Json.LastErrorText))          ! 'A string was never closed.'",

'EmailJsonClass.Construct':    "Json  EmailJsonClass                               ! Construct runs here, before your CODE",
'EmailJsonClass.Destruct':     "!  runs at program end: frees the node queue, the index and the document",
'EmailJsonClass.Parse':        "IF NOT MailApi.Json.Parse(MailApi.Net.Body()) THEN MESSAGE(MailApi.Json.LastErrorText).",
'EmailJsonClass.ClearAll':     "MailApi.Json.ClearAll()                            ! drop the document and its index",
'EmailJsonClass.Find':         "IF MailApi.Json.Find('contacts.0.email') THEN Loc:Have = 1.",
'EmailJsonClass.Has':          "IF NOT MailApi.Json.Has('errors') THEN Loc:Ok = 1.",
'EmailJsonClass.KindOf':       "IF MailApi.Json.KindOf('items') = ETJs:Array THEN DO ReadItems.",
'EmailJsonClass.Count':        "LOOP i = 0 TO MailApi.Json.Count('contacts') - 1; DO OneContact; END",
'EmailJsonClass.Value':        "Loc:Reason = MailApi.Json.Value('contacts.0.reason.message')",
'EmailJsonClass.ValueLong':    "Loc:Total = MailApi.Json.ValueLong('count')",
'EmailJsonClass.ValueReal':    "Loc:Rate = MailApi.Json.ValueReal('results.bounce_rate')",
'EmailJsonClass.ValueBool':    "IF MailApi.Json.ValueBool('data.0.is_verified') THEN Loc:Verified = 1.",
'EmailJsonClass.Raw':          "Loc:Row = MailApi.Json.Raw('contacts.0')           ! the whole object, for a log",
'EmailJsonClass.FirstArray':   "Loc:Path = MailApi.Json.FirstArray()               ! 'contacts', wherever they hung it",
'EmailJsonClass.FromUtf8':     "Loc:Text = MailApi.Json.FromUtf8(Loc:Utf8)         ! UTF-8 in, Windows-1252 out",
'EmailJsonClass.SetErr':       "RETURN SELF.SetErr(ETJs:Syntax, 'Expected a comma')  ! in a derived parser",

# =====================================================================
#  EmailApiClass  -  one class, every provider's management API
# =====================================================================
'EmailApiClass.Mailer':        "IF MailApi.Mailer.Acc.Provider = ETPrv:Brevo THEN DO BrevoOnly.",
'EmailApiClass.Net':           "MailApi.Net.Timeout = 60000                        ! a big block list is slow to fetch",
'EmailApiClass.Enc':           "Loc:Basic = MailApi.Enc.Base64('api:' & CLIP(Loc:Key))",
'EmailApiClass.Json':          "MESSAGE('The reply had ' & MailApi.Json.Count('') & ' members')",
'EmailApiClass.Account':       "MESSAGE('Plan: ' & CLIP(MailApi.Account.Plan) & ', ' & MailApi.Account.Credits & ' credits')",
'EmailApiClass.SuppQ':         "GET(MailApi.SuppQ, 1); MESSAGE(CLIP(MailApi.SuppQ.Address) & ' - ' & CLIP(MailApi.SuppQ.Reason))",
'EmailApiClass.StatQ':         "GET(MailApi.StatQ, 1); Loc:Sent = MailApi.StatQ.Delivered",
'EmailApiClass.EventQ':        "GET(MailApi.EventQ, 1); Loc:What = MailApi.EventQ.EventName   ! delivered / opened / bounced",
'EmailApiClass.ContactQ':      "GET(MailApi.ContactQ, 1); Loc:Email = MailApi.ContactQ.Address",
'EmailApiClass.ListQ':         "GET(MailApi.ListQ, 1); Loc:ListId = MailApi.ListQ.Id",
'EmailApiClass.CampaignQ':     "GET(MailApi.CampaignQ, 1); Loc:State = MailApi.CampaignQ.Status",
'EmailApiClass.TemplateQ':     "GET(MailApi.TemplateQ, 1); Loc:TplId = MailApi.TemplateQ.Id",
'EmailApiClass.SenderQ':       "GET(MailApi.SenderQ, 1); IF NOT MailApi.SenderQ.Verified THEN MESSAGE('Not verified yet').",
'EmailApiClass.DomainQ':       "GET(MailApi.DomainQ, 1); IF NOT MailApi.DomainQ.Dkim THEN MESSAGE('DKIM is not set up').",
'EmailApiClass.HookQ':         "GET(MailApi.HookQ, 1); Loc:Url = MailApi.HookQ.Url",
'EmailApiClass.Language':      "MailApi.Language = ETLng:Spanish                   ! the Manage window, in Spanish",
'EmailApiClass.Silent':        "MailApi.Silent = 1                                 ! never pop a box - a batch job",
'EmailApiClass.PageSize':      "MailApi.PageSize = 500                             ! ask for 500 rows a time, not 100",
'EmailApiClass.MaxRows':       "MailApi.MaxRows = 0                                ! no limit: read the whole block list",
'EmailApiClass.LastError':     "IF MailApi.LastError = ETApi:NotSupported THEN DISABLE(?Blocked).",
'EmailApiClass.LastErrorText': "MESSAGE(CLIP(MailApi.LastErrorText))               ! why the provider said no",
'EmailApiClass.LastStatus':    "IF MailApi.LastStatus = 401 THEN MESSAGE('The API key was rejected').",
'EmailApiClass.LastUrl':       "Log('asked for ' & CLIP(MailApi.LastUrl))          ! for a support call",
'EmailApiClass.ItemBase':      "Loc:Row = MailApi.Json.Raw(MailApi.ItemBase)       ! inside an override of MapItem",
'EmailApiClass.ArgId':         "MailApi.ArgId = '1234'; MailApi.Perform(ETOp:CampaignSend, 0)",
'EmailApiClass.ArgEmail':      "MailApi.ArgEmail = 'bob@acme.com'                  ! what {email} expands to",
'EmailApiClass.ArgText':       "MailApi.ArgText = 'New customers'                  ! what {text} expands to",
'EmailApiClass.ArgSubject':    "MailApi.ArgSubject = 'Our March offers'            ! what {subject} expands to",
'EmailApiClass.ArgHtml':       "IF NOT MailApi.ArgHtml &= NULL THEN Loc:Len = SIZE(MailApi.ArgHtml).",
'EmailApiClass.ArgFrom':       "MailApi.ArgFrom = TODAY() - 90                     ! what {ymdfrom} expands to",
'EmailApiClass.ArgTo':         "MailApi.ArgTo = TODAY()                            ! what {ymdto} expands to",
'EmailApiClass.ArgOffset':     "MESSAGE('Now reading from row ' & MailApi.ArgOffset)",

'EmailApiClass.Construct':     "MailApi  EmailApiClass                             ! Construct runs here, before your CODE",
'EmailApiClass.Destruct':      "!  runs at program end: frees the ten answer queues and the parser",
'EmailApiClass.Init':          "MailApi.Init(Mailer)                               ! borrows the account and the HTTPS layer",
'EmailApiClass.Supports':      "IF NOT MailApi.Supports(ETOp:Campaigns) THEN DISABLE(?Campaigns).",
'EmailApiClass.OpName':        "?Tab{PROP:Text} = MailApi.OpName(ETOp:Suppressions)   ! 'Blocked' / 'Bloqueados'",
'EmailApiClass.SuppKindName':  "Loc:What = MailApi.SuppKindName(ETSup:Bounce)      ! 'Bounce' / 'Rebote'",
'EmailApiClass.SuppKindOf':    "Loc:Kind = MailApi.SuppKindOf('hardBounce')        ! ETSup:Bounce",
'EmailApiClass.GetAccount':    "IF MailApi.GetAccount() THEN MESSAGE(CLIP(MailApi.Account.Company)).",
'EmailApiClass.GetSuppressions':"Loc:Rows = MailApi.GetSuppressions(ETSup:All)     ! -1 = the provider said no",
'EmailApiClass.GetStats':      "Loc:Days = MailApi.GetStats(TODAY() - 30, TODAY())",
'EmailApiClass.GetEvents':     "Loc:Rows = MailApi.GetEvents(TODAY() - 7, TODAY())",
'EmailApiClass.GetContacts':   "Loc:Rows = MailApi.GetContacts(Loc:ListId)         ! omit the id for all of them",
'EmailApiClass.GetLists':      "Loc:Rows = MailApi.GetLists()",
'EmailApiClass.GetCampaigns':  "Loc:Rows = MailApi.GetCampaigns()",
'EmailApiClass.GetTemplates':  "Loc:Rows = MailApi.GetTemplates()",
'EmailApiClass.GetSenders':    "Loc:Rows = MailApi.GetSenders()                    ! the addresses you may send from",
'EmailApiClass.GetDomains':    "Loc:Rows = MailApi.GetDomains()                    ! and whether SPF and DKIM are set up",
'EmailApiClass.GetWebhooks':   "Loc:Rows = MailApi.GetWebhooks()",
'EmailApiClass.DeleteSuppression':"IF MailApi.DeleteSuppression('bob@acme.com', ETSup:Bounce) THEN DO Reload.",
'EmailApiClass.DeleteAllSuppressions':"Loc:Gone = MailApi.DeleteAllSuppressions(ETSup:Bounce)   ! how many were let back in",
'EmailApiClass.AddSuppression':"MailApi.AddSuppression('leaver@acme.com', ETSup:Unsub, 'asked us to stop')",
'EmailApiClass.AddContact':    "MailApi.AddContact('new@acme.com', 'Ana Ruiz', Loc:ListId)",
'EmailApiClass.DeleteContact': "MailApi.DeleteContact('old@acme.com')              ! by address, or by the provider's id",
'EmailApiClass.AddList':       "IF MailApi.AddList('March newsletter') THEN DO Reload.",
'EmailApiClass.AddCampaign':   "MailApi.AddCampaign('March', 'Our March offers', Loc:Html, Loc:ListId)",
'EmailApiClass.SendCampaign':  "IF MailApi.SendCampaign(MailApi.ArgId) THEN MESSAGE('On its way').",
'EmailApiClass.AddWebhook':    "MailApi.AddWebhook('https://acme.com/mailhook')",
'EmailApiClass.DeleteWebhook': "MailApi.DeleteWebhook(Loc:HookId)",
'EmailApiClass.IsBlocked':     "IF MailApi.IsBlocked(CUS:EMail) THEN CYCLE.        ! do not mail a hard bounce again",
'EmailApiClass.ExportSuppressions':"Loc:Rows = MailApi.ExportSuppressions('blocked.csv')",
'EmailApiClass.RawCall':       "IF MailApi.RawCall('GET', '/v3/user/credits') = 200 THEN Loc:Body = MailApi.Net.Body().",
'EmailApiClass.Manage':        "MailApi.Manage(2)                                  ! straight to the blocked list",
'EmailApiClass.ShowError':     "IF MailApi.GetSuppressions() < 0 THEN MailApi.ShowError().",
'EmailApiClass.Txt':           "?Unblock{PROP:Text} = MailApi.Txt(ETATxt:Unblock)",
'EmailApiClass.SetErr':        "RETURN SELF.SetErr(ETApi:Refused, 'That list is empty')   ! in a derived class",
'EmailApiClass.BuildMap':      "PARENT.BuildMap(); SELF.Row(ETPrv:Custom, ETOp:Suppressions, ETSup:All, 'GET', Loc:Url)",
'EmailApiClass.Row':           "SELF.Row(ETPrv:Custom, ETOp:Stats, 0, 'GET', '{{scheme}{{host}/stats', 'days', 'When=@d')",
'EmailApiClass.FindRow':       "IF MailApi.FindRow(ETOp:Suppressions, ETSup:Spam) THEN Loc:Url = MailApi.MapQ.Url.",
'EmailApiClass.ExactRow':      "IF MailApi.ExactRow(ETOp:Suppressions, ETSup:Spam) THEN Loc:Separate = 1.",
'EmailApiClass.AuthHeaders':   "Loc:Hdrs = MailApi.AuthHeaders(ETOp:Suppressions)  ! the signed headers, ready to send",
'EmailApiClass.Expand':        "Loc:Url = MailApi.Expand('{{scheme}{{host}/v3/{{domain}/bounces')",
'EmailApiClass.RfcDate':       "Loc:When = MailApi.RfcDate(TODAY())                ! 'Mon, 24 Aug 2026 00:00:00 GMT'",
'EmailApiClass.Fetch':         "Loc:Rows = MailApi.Fetch(ETOp:Templates, 0)        ! the engine, under every Get method",
'EmailApiClass.MapItem':       "PARENT.MapItem(pOp, pKind, pMap); IF pOp = ETOp:Suppressions THEN DO ExtraColumn.",
'EmailApiClass.Perform':       "IF MailApi.Perform(ETOp:CampaignSend, 0) THEN MESSAGE('Sent').",
'EmailApiClass.MapText':       "Loc:Src = MailApi.MapText('Address=email;Reason=why', 'Reason')   ! 'why'",
'EmailApiClass.ItemVal':       "Loc:Addr = MailApi.ItemVal(pMap, 'Address')        ! inside an override of MapItem",
'EmailApiClass.ItemLong':      "Loc:Code = MailApi.ItemLong(pMap, 'Code')",
'EmailApiClass.ItemBool':      "Loc:Live = MailApi.ItemBool(pMap, 'Active')",
'EmailApiClass.ItemWhen':      "MailApi.ItemWhen(pMap, 'When', Loc:Date, Loc:Time)   ! epoch, ISO or RFC-2822",
'EmailApiClass.UrlEncode':     "Loc:Safe = MailApi.UrlEncode('a b+c@d.com')        ! a%20b%2Bc%40d.com",
'EmailApiClass.JsonStr':       "Loc:Escaped = MailApi.JsonStr(Loc:Text)            ! escaped, WITHOUT the quotes",
'EmailApiClass.Csv':           "Loc:Field = MailApi.Csv(MailApi.SuppQ.Reason)      ! quoted, commas and all",
'EmailApiClass.FailedText':    "Log(MailApi.FailedText())                          ! 'HTTP 401: {\"errors\":...'",

# =====================================================================
#  Signing - AWS Signature Version 4
# =====================================================================
'EmailNetClass.SignAws':       "Loc:Hdrs = Mailer.Net.SignAws('GET', Loc:Url, '', Loc:KeyId, Loc:Secret, 'eu-west-1', 'ses')",
'EmailNetClass.Hmac256':       "Loc:Mac = Mailer.Net.Hmac256(Loc:Key, 'Hi There')   ! 32 raw bytes, RFC 2104",
'EmailNetClass.HexOf':         "Loc:Hex = Mailer.Net.HexOf(Loc:Mac)                 ! 'b0344c61d8db...'",
'EmailNetClass.Sha256Hex':     "Loc:Hash = Mailer.Net.Sha256Hex(Loc:Body)           ! what the canonical request carries",
'EmailNetClass.SigningKey':    "Loc:Key = Mailer.Net.SigningKey(Loc:Secret, '20260824', 'eu-west-1', 'ses')",
'EmailNetClass.AmzStamp':      "Loc:When = Mailer.Net.AmzStamp()                    ! '20260824T134205Z', UTC",
'EmailNetClass.CanonPath':     "Loc:Path = Mailer.Net.CanonPath('/v2/email/x/a%40b.com')   ! '/v2/email/x/a%2540b.com'",
'EmailNetClass.CanonQuery':    "Loc:Q = Mailer.Net.CanonQuery('b=2&a=1')            ! 'a=1&b=2' - sorted",

'EmailApiClass.SignedHeaders': "Loc:Hdrs = MailApi.SignedHeaders(ETOp:Account, 'GET', Loc:Url, '')",
'EmailApiClass.AwsKeyId':      "Loc:Id = MailApi.AwsKeyId()                         ! ApiKey2, or UserName if blank",
'EmailApiClass.ArgToken':      "MESSAGE('Now reading from token ' & CLIP(MailApi.ArgToken))",
}
