# -*- coding: utf-8 -*-
# Every public member of WordDocClass and the WordDocTools classes, in the order
# the .inc files declare them: (signature, English, Spanish, code[, Spanish code]).
# Written from WordDocClass.inc/.clw and WordDocTools.inc/.clw - keep in step.

EQUATES = [
    ("WD:Toolbar", "1", "Init flags: the formatting toolbar", "Flags de Init: la barra de formato"),
    ("WD:ReadOnly", "2", "Init flags: view only", "Flags de Init: solo lectura"),
    ("WD:PageView", "4", "Init flags: the printed width on a grey desk", "Flags de Init: el ancho impreso sobre un fondo gris"),
    ("WD:NoBorder", "8", "Init flags: no frame", "Flags de Init: sin marco"),
    ("WD:Left WD:Right WD:Center WD:Justify", "1-4", "SetAlign, GetFormat(8), RtfFontClass.Align", "SetAlign, GetFormat(8), RtfFontClass.Align"),
    ("WD:NoList WD:Bullets WD:Numbers", "0-2", "SetList, GetFormat(9), RtfFontClass.List", "SetList, GetFormat(9), RtfFontClass.List"),
    ("WD:LowerLetters WD:UpperLetters", "3-4", "SetList: a. b. c. / A. B. C.", "SetList: a. b. c. / A. B. C."),
    ("WD:LowerRoman WD:UpperRoman", "5-6", "SetList: i. ii. iii. / I. II. III.", "SetList: i. ii. iii. / I. II. III."),
    ("WD:Off WD:On WD:Toggle", "0-2", "Bold, Italic, Underline, Strike", "Bold, Italic, Underline, Strike"),
    ("WD:LetterWidth", "9360", "line width of Letter paper with 1-inch margins, in twips", "ancho de l\u00ednea de un Letter con m\u00e1rgenes de 1 pulgada, en twips"),
    ("WD:A4Width", "9026", "the same for A4", "lo mismo para A4"),
    ("WD:Pages", "0", "PaginateForReport: pieces the size of the IMAGE", "PaginateForReport: trozos del tama\u00f1o del IMAGE"),
    ("WD:Flow", "1", "PaginateForReport: line by line, filling the room left on each page", "PaginateForReport: l\u00ednea a l\u00ednea, llenando el hueco de cada p\u00e1gina"),
]
EQUATES_CODE = """Doc1.Init(0{PROP:Handle}, ?DocRegion, WD:Toolbar + WD:PageView)
Doc1.SetAlign(WD:Justify)
Doc1.SetList(WD:UpperRoman)
Doc1.Bold(WD:On)
Doc1.SetPageWidth(WD:A4Width)"""

# ---------------------------------------------------------------------------
WORDDOC_PROPS_BEFORE = [
    ("ShowToolbar", "BYTE(1)", "show the formatting toolbar", "muestra la barra de formato", "Doc1.ShowToolbar = FALSE"),
    ("ReadOnly", "BYTE", "view only", "solo lectura", "Doc1.ReadOnly = TRUE"),
    ("PageView", "BYTE", "show the printed width on a grey desk (needs PageWidth)", "muestra el ancho impreso sobre un fondo gris (necesita PageWidth)", "Doc1.PageView = TRUE"),
    ("PageWidth", "LONG", "printed line width in twips; 0 wraps at the window edge", "ancho de l\u00ednea impreso en twips; 0 corta en el borde de la ventana", "Doc1.PageWidth = WD:LetterWidth"),
    ("DefaultFont", "CSTRING(32)", "font of a new document; blank = Segoe UI", "fuente de un documento nuevo; vac\u00edo = Segoe UI", "Doc1.DefaultFont = 'Calibri'"),
    ("DefaultSize", "REAL", "its size in points; 0 = 11", "su tama\u00f1o en puntos; 0 = 11", "Doc1.DefaultSize = 12"),
]
WORDDOC_PROPS_RO = [
    ("Err", "LONG", "not 0 when Init / InitHidden failed: the step that failed", "distinto de 0 si Init / InitHidden fall\u00f3: el paso que fall\u00f3", "IF Doc1.Err THEN MESSAGE('Editor: ' & Doc1.Err)."),
    ("Pages", "LONG", "pieces made by the last Paginate", "trozos creados por el \u00faltimo Paginate", "LOOP P# = 1 TO Doc1.Pages"),
]

WORDDOC_GROUPS = [
 (("Life cycle", "Ciclo de vida"), [
  ("Init(LONG pWinHandle, LONG pFeq, LONG pFlags=-1),BYTE,PROC",
   "Creates the editor over a REGION placed in the window formatter. With <code>pFlags = -1</code> the flags come from ShowToolbar, ReadOnly and PageView. Returns FALSE and sets <code>Err</code> on failure.",
   "Crea el editor encima de una REGION colocada en el dise\u00f1ador de ventanas. Con <code>pFlags = -1</code> los flags salen de ShowToolbar, ReadOnly y PageView. Devuelve FALSE y rellena <code>Err</code> si falla.",
   "OPEN(Window)\nDoc1.PageWidth = WD:LetterWidth\nIF NOT Doc1.Init(0{PROP:Handle}, ?DocRegion) THEN MESSAGE('No editor: ' & Doc1.Err).",
   "OPEN(Window)\nDoc1.PageWidth = WD:LetterWidth\nIF NOT Doc1.Init(0{PROP:Handle}, ?DocRegion) THEN MESSAGE('Sin editor: ' & Doc1.Err)."),
  ("InitHidden(),BYTE,PROC",
   "An invisible document with no window: for reports, exports and batch work.",
   "Un documento invisible, sin ventana: para informes, exportaciones y procesos por lotes.",
   "Doc1.InitHidden()\nDoc1.LoadBlob(DOC:Body)"),
  ("Kill()",
   "Destroys the editor and deletes the page files it wrote. Call it before <code>CLOSE(Window)</code>; the destructor runs it again harmlessly.",
   "Destruye el editor y borra los ficheros de p\u00e1gina que escribi\u00f3. Ll\u00e1malo antes de <code>CLOSE(Window)</code>; el destructor lo repite sin problema.",
   "Doc1.Kill()\nCLOSE(Window)"),
  ("TakeEvent(),BYTE,PROC",
   "Call it for every event in the ACCEPT loop. It keeps the editor over its REGION when the window is resized or a TAB changes, and returns TRUE while the document has unsaved changes.",
   "Ll\u00e1malo en cada evento del bucle ACCEPT. Mantiene el editor sobre su REGION al redimensionar la ventana o cambiar de TAB, y devuelve TRUE mientras haya cambios sin guardar.",
   "ACCEPT\n  IF Doc1.TakeEvent() THEN ENABLE(?SaveButton) ELSE DISABLE(?SaveButton).\nEND"),
  ("Reposition()",
   "Moves the editor to its REGION now. TakeEvent does this for you; call it after moving or hiding the REGION from code.",
   "Coloca el editor sobre su REGION ahora mismo. TakeEvent ya lo hace; ll\u00e1malo si mueves u ocultas la REGION desde c\u00f3digo.",
   "?DocRegion{PROP:Height} = ?DocRegion{PROP:Height} + 50\nDoc1.Reposition()"),
  ("Alive(),BYTE", "TRUE while the editor exists.", "TRUE mientras el editor exista.",
   "IF Doc1.Alive() THEN Doc1.SaveBlob(DOC:Body)."),
  ("Hwnd(),LONG", "The Windows handle of the editor (its host window), for API calls of your own.",
   "El handle de Windows del editor (su ventana anfitriona), para tus propias llamadas a la API.",
   "SetFocus(Doc1.Hwnd())                 ! SetFocus prototyped in your MAP",
   "SetFocus(Doc1.Hwnd())                 ! SetFocus declarado en tu MAP"),
  ("Slot(),LONG", "The document's number inside wdoc.c. The tool classes use it; you seldom need it.",
   "El n\u00famero del documento dentro de wdoc.c. Lo usan las clases de herramientas; rara vez lo necesitar\u00e1s.",
   "IF Doc1.Slot() = 0 THEN MESSAGE('Not initialised').",
   "IF Doc1.Slot() = 0 THEN MESSAGE('Sin inicializar')."),
  ("StructSizes(),LONG", "A self-test: 84188 when the C structures match Win32 (CHARFORMAT2 84 bytes, PARAFORMAT2 188).",
   "Una autoprueba: 84188 cuando las estructuras C coinciden con Win32 (CHARFORMAT2 84 bytes, PARAFORMAT2 188).",
   "IF Doc1.StructSizes() <> 84188 THEN MESSAGE('wdoc.c built with the wrong packing').",
   "IF Doc1.StructSizes() <> 84188 THEN MESSAGE('wdoc.c compilado con otro empaquetado')."),
 ]),
 (("Content", "Contenido"), [
  ("LoadBlob(*BLOB pBlob)", "Loads RTF, or plain text, from a BLOB. Clears the undo history and the modified flag.",
   "Carga RTF, o texto plano, desde un BLOB. Vac\u00eda el historial de deshacer y la marca de modificado.",
   "Doc1.LoadBlob(DOC:Body)"),
  ("SaveBlob(*BLOB pBlob)", "Writes the document into the BLOB as RTF and clears the modified flag. Then write the record as usual.",
   "Escribe el documento en el BLOB como RTF y quita la marca de modificado. Despu\u00e9s graba el registro como siempre.",
   "Doc1.SaveBlob(DOC:Body)\nAccess:Docs.Update()"),
  ("LoadString(STRING pRtfOrText)", "Loads from a string. One that starts with <code>{\\rtf</code> is RTF, anything else plain text.",
   "Carga desde una cadena. Si empieza por <code>{\\rtf</code> es RTF; si no, texto plano.",
   "Doc1.LoadString('Dear customer,<13,10>Thank you for your order.')",
   "Doc1.LoadString('Estimado cliente:<13,10>Gracias por su pedido.')"),
  ("GetRtf(),STRING", "The whole document as RTF.", "Todo el documento como RTF.", "L:Rtf = Doc1.GetRtf()"),
  ("GetText(),STRING", "The document as plain text (RtfTextClass gives more control over lists and tables).",
   "El documento como texto plano (RtfTextClass da m\u00e1s control sobre listas y tablas).", "DOC:Words = Doc1.GetText()"),
  ("LoadFile(STRING pFileName),BYTE,PROC", "Loads an .rtf (or .txt) file.", "Carga un fichero .rtf (o .txt).",
   "IF NOT Doc1.LoadFile('C:\\Letters\\welcome.rtf') THEN MESSAGE('Cannot open the file').",
   "IF NOT Doc1.LoadFile('C:\\Cartas\\bienvenida.rtf') THEN MESSAGE('No se puede abrir').") ,
  ("SaveFile(STRING pFileName),BYTE,PROC", "Saves the document as an .rtf file that Word and WordPad open.",
   "Guarda el documento como un .rtf que abren Word y WordPad.",
   "Doc1.SaveFile('C:\\Letters\\' & CLIP(CUS:Code) & '.rtf')",
   "Doc1.SaveFile('C:\\Cartas\\' & CLIP(CLI:Codigo) & '.rtf')"),
  ("ClearAll()", "Empties the document.", "Vac\u00eda el documento.", "Doc1.ClearAll()"),
  ("Length(),LONG", "The number of characters.", "El n\u00famero de caracteres.",
   "?Count{PROP:Text} = Doc1.Length() & ' characters'", "?Count{PROP:Text} = Doc1.Length() & ' caracteres'"),
  ("Modified(),BYTE", "TRUE when the user changed the document since it was loaded or saved.",
   "TRUE si el usuario cambi\u00f3 el documento desde que se carg\u00f3 o guard\u00f3.",
   "IF Doc1.Modified() THEN Doc1.SaveBlob(DOC:Body)."),
  ("SetModified(BYTE pOn)", "Sets or clears the modified flag.", "Pone o quita la marca de modificado.",
   "Doc1.SetModified(FALSE)              ! after saving it somewhere yourself",
   "Doc1.SetModified(FALSE)              ! tras guardarlo t\u00fa en otro sitio"),
 ]),
 (("Inserting at the caret", "Insertar en el cursor"), [
  ("InsertText(STRING pText)", "Types text at the caret, replacing the selection.", "Escribe texto en el cursor, sustituyendo la selecci\u00f3n.",
   "Doc1.InsertText('Kind regards,<13,10>' & CLIP(USE:Name))", "Doc1.InsertText('Un saludo,<13,10>' & CLIP(USU:Nombre))"),
  ("InsertRtf(STRING pRtf)", "Inserts formatted RTF at the caret.", "Inserta RTF con formato en el cursor.",
   "Doc1.InsertRtf('{{\\rtf1{{\\b Important:} read before signing.}')",
   "Doc1.InsertRtf('{{\\rtf1{{\\b Importante:} l\\''e9alo antes de firmar.}')"),
  ("InsertImage(STRING pFileName, LONG pMaxWidthTw=0),LONG,PROC",
   "Inserts a PNG, JPEG, BMP, EMF or WMF picture, scaled down to <code>pMaxWidthTw</code> (0 = the page width). Returns 1 on success, -1 when the file cannot be read, -2 for any other format, -3 when out of memory.",
   "Inserta una imagen PNG, JPEG, BMP, EMF o WMF, reducida a <code>pMaxWidthTw</code> (0 = el ancho de p\u00e1gina). Devuelve 1 si va bien, -1 si no se puede leer, -2 si es otro formato, -3 sin memoria.",
   "IF Doc1.InsertImage(CUS:LogoFile, 2880) <> 1 THEN MESSAGE('Not a picture I can use').",
   "IF Doc1.InsertImage(CLI:Logo, 2880) <> 1 THEN MESSAGE('No es una imagen v\u00e1lida')."),
  ("InsertTable(LONG pRows, LONG pCols, LONG pWidthTw=0),BYTE,PROC",
   "Inserts a table with thin borders, spread over <code>pWidthTw</code> (0 = the page width).",
   "Inserta una tabla con bordes finos, repartida en <code>pWidthTw</code> (0 = el ancho de p\u00e1gina).",
   "Doc1.InsertTable(4, 3)                ! 4 rows, 3 columns", "Doc1.InsertTable(4, 3)                ! 4 filas, 3 columnas"),
 ]),
 (("Formatting the selection", "Formato de la selecci\u00f3n"), [
  ("Bold / Italic / Underline / Strike (BYTE pHow=WD:Toggle)", "Switch the style on, off or over.", "Activan, desactivan o alternan el estilo.",
   "Doc1.SelectText(0, 12)\nDoc1.Bold(WD:On)\nDoc1.Italic()                         ! toggles\nDoc1.Underline(WD:Off)\nDoc1.Strike(WD:Toggle)",
   "Doc1.SelectText(0, 12)\nDoc1.Bold(WD:On)\nDoc1.Italic()                         ! alterna\nDoc1.Underline(WD:Off)\nDoc1.Strike(WD:Toggle)"),
  ("SetFont(STRING pFace)", "The font of the selection.", "La fuente de la selecci\u00f3n.", "Doc1.SetFont('Georgia')"),
  ("SetFontSize(REAL pPoints)", "The size of the selection.", "El tama\u00f1o de la selecci\u00f3n.", "Doc1.SetFontSize(14)"),
  ("SetColor(LONG pColor)", "The text colour; COLOR:None = automatic.", "El color del texto; COLOR:None = autom\u00e1tico.", "Doc1.SetColor(COLOR:Red)"),
  ("SetHighlight(LONG pColor)", "The highlighter colour behind the text; COLOR:None takes it off.", "El color de resaltado tras el texto; COLOR:None lo quita.", "Doc1.SetHighlight(COLOR:Yellow)"),
  ("SetAlign(BYTE pAlign)", "Aligns the paragraphs in the selection.", "Alinea los p\u00e1rrafos de la selecci\u00f3n.", "Doc1.SetAlign(WD:Center)"),
  ("SetList(BYTE pStyle)", "Bullets or numbering for the paragraphs in the selection; WD:NoList removes it.", "Vi\u00f1etas o numeraci\u00f3n para los p\u00e1rrafos de la selecci\u00f3n; WD:NoList la quita.", "Doc1.SetList(WD:Numbers)"),
  ("Indent / Outdent (LONG pTwips=360)", "Move the paragraphs right or left.", "Mueven los p\u00e1rrafos a la derecha o a la izquierda.",
   "Doc1.Indent()                         ! a quarter of an inch\nDoc1.Outdent(720)                     ! half an inch back",
   "Doc1.Indent()                         ! un cuarto de pulgada\nDoc1.Outdent(720)                     ! media pulgada atr\u00e1s"),
  ("GetFont(),STRING", "The font of the selection; blank when it mixes fonts.", "La fuente de la selecci\u00f3n; vac\u00eda si mezcla fuentes.", "?FontName{PROP:Text} = Doc1.GetFont()"),
  ("GetFormat(LONG pWhich),LONG",
   "One detail of the selection: 1 bold, 2 italic, 3 underline, 4 strike (1/0), 5 size in points &times; 10, 6 text colour (0 = automatic), 7 highlight (0FFFFFFh = none), 8 alignment, 9 list style. -1 when mixed. RtfFontClass.Read gives them all at once.",
   "Un detalle de la selecci\u00f3n: 1 negrita, 2 cursiva, 3 subrayado, 4 tachado (1/0), 5 tama\u00f1o en puntos &times; 10, 6 color (0 = autom\u00e1tico), 7 resaltado (0FFFFFFh = ninguno), 8 alineaci\u00f3n, 9 lista. -1 si est\u00e1 mezclado. RtfFontClass.Read los da todos a la vez.",
   "IF Doc1.GetFormat(1) = 1 THEN ?BoldBtn{PROP:Icon} = 'boldon.ico'.\nL:Points = Doc1.GetFormat(5) / 10"),
 ]),
 (("Editing and undo", "Edici\u00f3n y deshacer"), [
  ("Undo() / Redo()", "The same as Ctrl+Z / Ctrl+Y. A whole tool operation (Replace All, a merge, Set Font) is one step.",
   "Lo mismo que Ctrl+Z / Ctrl+Y. Una operaci\u00f3n de herramienta entera (Reemplazar todo, una combinaci\u00f3n, cambiar fuente) es un solo paso.",
   "Doc1.Undo()\nDoc1.Redo()"),
  ("CanUndo(),BYTE / CanRedo(),BYTE", "Whether there is something to undo or redo.", "Si hay algo que deshacer o rehacer.",
   "IF Doc1.CanUndo() THEN ENABLE(?UndoBtn) ELSE DISABLE(?UndoBtn)."),
  ("ClearUndo()", "Forgets the undo history. The Load methods do this for you.", "Olvida el historial de deshacer. Los m\u00e9todos Load ya lo hacen.", "Doc1.ClearUndo()"),
  ("SetUndoLimit(LONG pSteps)", "How many steps are kept (100 by default).", "Cu\u00e1ntos pasos se guardan (100 por defecto).", "Doc1.SetUndoLimit(500)"),
  ("BeginUndoGroup() / EndUndoGroup()", "Everything in between undoes as one step. Pairs nest.", "Todo lo que hay entre ambos se deshace en un paso. Los pares se pueden anidar.",
   "Doc1.BeginUndoGroup()\nDoc1.InsertText('Re: ' & CLIP(ORD:Number))\nDoc1.SelectText(0, 3)\nDoc1.Bold(WD:On)\nDoc1.EndUndoGroup()"),
  ("CutText() / CopyText() / PasteText()", "The clipboard, like Ctrl+X / Ctrl+C / Ctrl+V.", "El portapapeles, como Ctrl+X / Ctrl+C / Ctrl+V.", "Doc1.SelectAll()\nDoc1.CopyText()"),
  ("SelectAll()", "Selects the whole document.", "Selecciona todo el documento.", "Doc1.SelectAll()\nDoc1.SetFont('Arial')"),
  ("SelectText(LONG pFrom, LONG pTo)", "Selects a range; pTo = -1 is the end. SelectText(N, N) puts the caret at N.",
   "Selecciona un rango; pTo = -1 es el final. SelectText(N, N) pone el cursor en N.",
   "Doc1.SelectText(0, 0)                 ! caret at the top\nDoc1.SelectText(Doc1.Length(), Doc1.Length())   ! caret at the end",
   "Doc1.SelectText(0, 0)                 ! cursor al principio\nDoc1.SelectText(Doc1.Length(), Doc1.Length())   ! cursor al final"),
  ("Find(STRING pText, BYTE pMatchCase=0, BYTE pWholeWord=0),LONG,PROC",
   "Selects the next match after the caret, going round to the top. Returns its position or -1. RtfSearchClass does more.",
   "Selecciona la siguiente coincidencia tras el cursor, volviendo al principio. Devuelve su posici\u00f3n o -1. RtfSearchClass hace m\u00e1s.",
   "IF Doc1.Find('total', FALSE, TRUE) < 0 THEN MESSAGE('Not found').", "IF Doc1.Find('total', FALSE, TRUE) < 0 THEN MESSAGE('No encontrado')."),
  ("Focus()", "Puts the keyboard focus in the editor.", "Pone el foco del teclado en el editor.", "Doc1.Focus()"),
  ("SetReadOnly(BYTE pOn)", "Locks or unlocks the document while it is open.", "Bloquea o desbloquea el documento con la ventana abierta.", "Doc1.SetReadOnly(CHOOSE(DOC:Signed = TRUE))"),
  ("SetToolbar(BYTE pOn)", "Shows or hides the toolbar while it is open.", "Muestra u oculta la barra con la ventana abierta.", "Doc1.SetToolbar(FALSE)"),
  ("SetZoom(LONG pPercent)", "Zooms the view; 0 = 100%.", "Ampl\u00eda la vista; 0 = 100%.", "Doc1.SetZoom(150)"),
  ("SetPaperColor(LONG pColor)", "The colour behind the text on screen; COLOR:None = the window colour.", "El color detr\u00e1s del texto en pantalla; COLOR:None = el de la ventana.",
   "Doc1.SetPaperColor(0F0FFFFh)          ! pale cream", "Doc1.SetPaperColor(0F0FFFFh)          ! crema claro"),
  ("SetPageWidth(LONG pTwips)", "Wraps the lines at the printed width, so they break where they will on paper; 0 wraps at the window edge.",
   "Corta las l\u00edneas al ancho impreso, para que partan donde partir\u00e1n en papel; 0 corta en el borde de la ventana.", "Doc1.SetPageWidth(WD:A4Width)"),
 ]),
 (("Printing", "Impresi\u00f3n"), [
  ("Paginate(LONG pWidthTw, LONG pHeightTw),LONG,PROC", "Splits the document into pages of that size and returns how many.",
   "Divide el documento en p\u00e1ginas de ese tama\u00f1o y devuelve cu\u00e1ntas.", "Pages# = Doc1.Paginate(WD:LetterWidth, 12960)     ! 6.5 x 9 in"),
  ("RenderPage(LONG pPage),STRING", "Writes page N into the temp folder as a WMF and returns the file name. Kill deletes those files.",
   "Escribe la p\u00e1gina N en la carpeta temporal como WMF y devuelve el nombre. Kill borra esos ficheros.",
   "?Preview{PROP:Text} = Doc1.RenderPage(1)          ! page 1 on an IMAGE", "?Preview{PROP:Text} = Doc1.RenderPage(1)          ! p\u00e1gina 1 en un IMAGE"),
  ("RenderPageTo(LONG pPage, STRING pFileName),BYTE,PROC", "Writes page N to a file you name: an EMF for .emf, a placeable WMF for .wmf.",
   "Escribe la p\u00e1gina N en el fichero que digas: EMF para .emf, WMF placeable para .wmf.", "Doc1.RenderPageTo(1, 'C:\\Out\\page1.emf')"),
  ("PageUsedHeight(LONG pPage),LONG", "How many twips of page N the text really fills.", "Cu\u00e1ntos twips de la p\u00e1gina N ocupa realmente el texto.",
   "IF Doc1.PageUsedHeight(Doc1.Pages) < 1440 THEN MESSAGE('The last page is almost empty').",
   "IF Doc1.PageUsedHeight(Doc1.Pages) < 1440 THEN MESSAGE('La \u00faltima p\u00e1gina est\u00e1 casi vac\u00eda')."),
  ("PaginateForReport(*REPORT pReport, LONG pImageFeq, BYTE pMode=0),LONG",
   "Measures the report IMAGE and cuts the document to fit it. WD:Pages makes pieces the size of the IMAGE; WD:Flow cuts one line per band, so the document starts in whatever room is left on the page. Returns the number of pieces.",
   "Mide el IMAGE del informe y corta el documento a su medida. WD:Pages hace trozos del tama\u00f1o del IMAGE; WD:Flow corta una l\u00ednea por banda, as\u00ed el documento empieza en el hueco que quede en la p\u00e1gina. Devuelve el n\u00famero de trozos.",
   "LOOP P# = 1 TO Doc1.PaginateForReport(Report, ?DocImage, WD:Flow)\n  Doc1.PreparePage(Report, ?DocImage, P#)\n  PRINT(RPT:DocBand)\nEND"),
  ("PreparePage(*REPORT pReport, LONG pImageFeq, LONG pPage, BYTE pShrinkLast=1)",
   "Points the IMAGE at piece N and sizes it and its band. With WD:Pages, pShrinkLast shrinks the last piece to its text, so what follows comes straight after it.",
   "Apunta el IMAGE al trozo N y ajusta su tama\u00f1o y el de su banda. Con WD:Pages, pShrinkLast encoge el \u00faltimo trozo a su texto, para que lo siguiente salga justo detr\u00e1s.",
   "Doc1.PreparePage(Report, ?DocImage, P#, FALSE)    ! keep the full height\nPRINT(RPT:DocBand)",
   "Doc1.PreparePage(Report, ?DocImage, P#, FALSE)    ! altura completa\nPRINT(RPT:DocBand)"),
 ]),
]

# ---------------------------------------------------------------------------
BASE = [
 ("Doc (&amp;WordDocClass)", "The document the tool works on: any WordDocClass method can be called on it.",
  "El documento sobre el que trabaja la herramienta: admite cualquier m\u00e9todo de WordDocClass.",
  "Search.LoadBlob(DOC:Body)\nSearch.Doc.SetFont('Arial')"),
 ("Attach(*WordDocClass pDoc)", "Works on an existing document: an editor on a window, or a report's hidden document.",
  "Trabaja sobre un documento existente: un editor en una ventana o el documento oculto de un informe.", "Search.Attach(Doc1)"),
 ("LoadString / LoadBlob / LoadFile (...),BYTE,PROC", "Load into the tool's own hidden document (or into the attached one).",
  "Cargan en el documento oculto propio de la herramienta (o en el adjunto).",
  "Text.LoadBlob(DOC:Body)\nHtml.LoadFile('C:\\Letters\\welcome.rtf')\nMd.LoadString(L:Rtf)"),
 ("SaveBlob(*BLOB pBlob) / SaveFile(STRING pFileName),BYTE,PROC", "Keep the changed document.", "Guardan el documento cambiado.",
  "Search.ReplaceAll('2025', '2026')\nSearch.SaveBlob(DOC:Body)"),
 ("GetRtf(),STRING", "The document as RTF.", "El documento como RTF.", "LET:Body = Merge.GetRtf()"),
 ("Ready(),BYTE", "TRUE when there is a document to work on.", "TRUE si hay un documento con el que trabajar.", "IF NOT Text.Ready() THEN Text.LoadBlob(DOC:Body)."),
 ("Undo() / Redo() / CanUndo(),BYTE", "The document's undo; each tool operation is one step.", "El deshacer del documento; cada operaci\u00f3n es un paso.",
  "Search.ReplaceAll('Mr', 'Ms')\nIF Search.CanUndo() THEN Search.Undo()."),
 ("Kill()", "Lets go of the document; a hidden one the tool made is destroyed. The destructor does the same.",
  "Suelta el documento; si era uno oculto creado por la herramienta, lo destruye. El destructor hace lo mismo.", "Search.Kill()"),
]

TOOLS = [
 ("rtfsearch", "RtfSearchClass",
  ("Find, count, replace and highlight.", "Buscar, contar, reemplazar y resaltar."),
  [("MatchCase", "BYTE", '"Smith" does not find "smith"', '"Smith" no encuentra "smith"', "Search.MatchCase = TRUE"),
   ("WholeWord", "BYTE", '"art" does not find "party"', '"arte" no encuentra "artesano"', "Search.WholeWord = TRUE"),
   ("Wrap", "BYTE(1)", "FindNext / FindPrevious go round the end", "FindNext / FindPrevious dan la vuelta al llegar al final", "Search.Wrap = FALSE"),
   ("SelectHits", "BYTE(1)", "select and scroll to each hit", "selecciona cada coincidencia y la hace visible", "Search.SelectHits = FALSE"),
   ("FoundAt", "LONG", "where the last hit starts; -1 = none", "d\u00f3nde empieza la \u00faltima coincidencia; -1 = ninguna", "IF Search.FoundAt >= 0 THEN ..."),
   ("FoundEnd", "LONG", "where it ends", "d\u00f3nde termina", "L:Len = Search.FoundEnd - Search.FoundAt"),
   ("What", "CSTRING(1024)", "what the last Find looked for", "lo que busc\u00f3 el \u00faltimo Find", "Search.What = L:Find"),
  ],
  [("Find(STRING pText),LONG,PROC", "The first hit from the top; its position or -1.", "La primera coincidencia desde el principio; su posici\u00f3n o -1.",
    "IF Search.Find('overdue') < 0 THEN MESSAGE('No overdue items').", "IF Search.Find('vencido') < 0 THEN MESSAGE('Nada vencido')."),
   ("FindNext(),LONG,PROC / FindPrevious(),LONG,PROC", "The next or previous hit of <code>What</code>.", "La coincidencia siguiente o anterior de <code>What</code>.",
    "Search.Wrap = FALSE\nIF Search.Find('total') >= 0\n  LOOP\n    ResultQ:Pos = Search.FoundAt\n    ADD(ResultQ)\n    IF Search.FindNext() < 0 THEN BREAK.\n  END\nEND"),
   ("Count(STRING pText),LONG", "How many hits there are.", "Cu\u00e1ntas coincidencias hay.",
    "?Info{PROP:Text} = Search.Count('Clarion') & ' mentions'", "?Info{PROP:Text} = Search.Count('Clarion') & ' menciones'"),
   ("Replace(STRING pFind, STRING pWith),BYTE,PROC", "Like Word's Replace button: the first call finds; each later call replaces the hit showing and finds the next. TRUE when it replaced one.",
    "Como el bot\u00f3n Reemplazar de Word: la primera llamada busca; cada llamada siguiente reemplaza la coincidencia visible y busca la siguiente. TRUE si reemplaz\u00f3.",
    "OF ?ReplaceBtn\n  Search.Replace(L:Find, L:With)"),
   ("ReplaceAll(STRING pFind, STRING pWith),LONG,PROC", "Replaces every hit, keeping each one's formatting; returns how many. One Undo takes them all back.",
    "Reemplaza todas, conservando el formato de cada una; devuelve cu\u00e1ntas. Un solo Deshacer las recupera todas.",
    "MESSAGE(Search.ReplaceAll('Acme Ltd', 'Acme Limited') & ' replaced')", "MESSAGE(Search.ReplaceAll('Acme SL', 'Acme S.L.') & ' reemplazos')"),
   ("HighlightAll(STRING pText, LONG pColor=COLOR:Yellow),LONG,PROC", "Paints every hit with a highlight; COLOR:None takes it off again.",
    "Resalta todas las coincidencias; COLOR:None quita el resaltado.", "Search.HighlightAll(L:Find)\nSearch.HighlightAll(L:Find, COLOR:None)"),
   ("Context(LONG pChars=40),STRING", "The plain text around the last hit, with ... where it was cut.", "El texto alrededor de la \u00faltima coincidencia, con ... donde se corta.",
    "IF Search.Find(L:Find) >= 0 THEN ResultQ:Line = Search.Context(30); ADD(ResultQ)."),
   ("TextAt(LONG pFrom, LONG pTo),STRING", "The plain text of a range.", "El texto plano de un rango.", "L:Word = Search.TextAt(Search.FoundAt, Search.FoundEnd)"),
  ]),
 ("rtffont", "RtfFontClass",
  ("Which font am I on, and the fonts a document uses.", "En qu\u00e9 fuente estoy y qu\u00e9 fuentes usa el documento."),
  [("Face", "CSTRING(32)", "the font; '' = mixed", "la fuente; '' = mezcladas", "?Font{PROP:Text} = Font.Face"),
   ("Size", "REAL", "points; 0 = mixed", "puntos; 0 = mezclados", "IF Font.Size > 14 THEN ..."),
   ("Bold Italic Underline Strike", "LONG", "1 on, 0 off, -1 mixed", "1 s\u00ed, 0 no, -1 mezclado", "L:IsBold = CHOOSE(Font.Bold = 1)"),
   ("Script", "LONG", "0 normal, 1 superscript, 2 subscript, -1 mixed", "0 normal, 1 super\u00edndice, 2 sub\u00edndice, -1 mezclado", "IF Font.Script = 1 THEN ..."),
   ("Color", "LONG", "text colour; COLOR:None automatic, -2 mixed", "color del texto; COLOR:None autom\u00e1tico, -2 mezclado", "?Swatch{PROP:Fill} = Font.Color"),
   ("Highlight", "LONG", "highlight; COLOR:None none, -2 mixed", "resaltado; COLOR:None ninguno, -2 mezclado", "IF Font.Highlight <> COLOR:None THEN ..."),
   ("Align", "LONG", "WD:Left..WD:Justify, -1 mixed", "WD:Left..WD:Justify, -1 mezclado", "IF Font.Align = WD:Center THEN ..."),
   ("List", "LONG", "WD:NoList..WD:UpperRoman, -1 mixed", "WD:NoList..WD:UpperRoman, -1 mezclado", "IF Font.List = WD:Bullets THEN ..."),
  ],
  [("Read(LONG pPos=-1),BYTE,PROC", "Fills the properties from the selection (-1) or from the character at pPos.", "Rellena las propiedades desde la selecci\u00f3n (-1) o desde el car\u00e1cter en pPos.",
    "OF EVENT:Timer\n  Font.Read()                         ! what font am I on?\n  ?Status{PROP:Text} = Font.Describe()",
    "OF EVENT:Timer\n  Font.Read()                         ! \u00bfen qu\u00e9 fuente estoy?\n  ?Status{PROP:Text} = Font.Describe()"),
   ("Describe(),STRING", "The last Read in words (English).", "El \u00faltimo Read en palabras (en ingl\u00e9s).", "MESSAGE(Font.Describe())              ! 'Georgia 12pt, bold, italic'"),
   ("FontCount(),LONG", "Scans the document; how many fonts it uses. Call it before FontName and FontChars.", "Recorre el documento; cu\u00e1ntas fuentes usa. Ll\u00e1malo antes de FontName y FontChars.",
    "IF Font.FontCount() > 3 THEN MESSAGE('Too many fonts').", "IF Font.FontCount() > 3 THEN MESSAGE('Demasiadas fuentes')."),
   ("FontName(LONG pN),STRING / FontChars(LONG pN),LONG", "Font N, and how many characters are set in it.", "La fuente N y cu\u00e1ntos caracteres la usan.",
    "LOOP I# = 1 TO Font.FontCount()\n  FontQ:Name = Font.FontName(I#)\n  FontQ:Chars = Font.FontChars(I#)\n  ADD(FontQ)\nEND"),
   ("FontList(<STRING pSep>),STRING", "Every font in one string, separated by pSep (default ', ').", "Todas las fuentes en una cadena, separadas por pSep (', ' por defecto).",
    "?Fonts{PROP:Text} = Font.FontList()\nL:Lines = Font.FontList('<13,10>')"),
   ("MainFont(),STRING", "The font most of the text uses.", "La fuente que usa la mayor parte del texto.", "IF Font.MainFont() <> 'Segoe UI' THEN Font.SetFontAll('Segoe UI')."),
   ("ReplaceFont(STRING pOld, STRING pNew),LONG,PROC", "Everything in one font goes into another; returns how many stretches changed.", "Todo lo que est\u00e1 en una fuente pasa a otra; devuelve cu\u00e1ntos tramos cambiaron.",
    "Font.ReplaceFont('Times New Roman', 'Georgia')"),
   ("SetFontAll(STRING pFace, REAL pPoints=0)", "The whole document in one font and/or size; '' or 0 leaves that part alone.", "Todo el documento en una fuente y/o tama\u00f1o; '' o 0 lo deja como est\u00e1.",
    "Font.SetFontAll('Calibri', 11)\nFont.SetFontAll('', 12)               ! size only", "Font.SetFontAll('Calibri', 11)\nFont.SetFontAll('', 12)               ! solo el tama\u00f1o"),
   ("SetFontRange(LONG pFrom, LONG pTo, STRING pFace, REAL pPoints=0)", "The same for a range; pTo = -1 is the end.", "Lo mismo para un rango; pTo = -1 es el final.",
    "Font.SetFontRange(0, 15, 'Georgia', 20)    ! the title", "Font.SetFontRange(0, 15, 'Georgia', 20)    ! el t\u00edtulo"),
   ("ScaleSizes(LONG pPercent),LONG,PROC", "Every size times a percentage, never under 4 pt.", "Cada tama\u00f1o por un porcentaje, nunca menos de 4 pt.",
    "Font.ScaleSizes(120)                  ! large-print copy", "Font.ScaleSizes(120)                  ! copia en letra grande"),
  ]),
 ("rtftext", "RtfTextClass",
  ("RTF to plain text, counts and excerpts.", "RTF a texto plano, recuentos y extractos."),
  [("ListPrefixes", "BYTE(1)", "- before bullets, 1. b. iv. before numbered items", "- delante de vi\u00f1etas, 1. b. iv. delante de elementos numerados", "Text.ListPrefixes = FALSE"),
   ("Bullet", "CSTRING(16)", "what a bullet becomes; '' = '- '", "en qu\u00e9 se convierte una vi\u00f1eta; '' = '- '", "Text.Bullet = '* '"),
   ("TabCells", "BYTE(1)", "table cells separated by TAB; off = ' | '", "celdas separadas por TAB; desactivado = ' | '", "Text.TabCells = FALSE"),
   ("PictureMarks", "BYTE", "write [picture] where a picture was", "escribe [picture] donde hab\u00eda una imagen", "Text.PictureMarks = TRUE"),
   ("Utf8", "BYTE", "UTF-8 instead of the ANSI code page", "UTF-8 en vez de la p\u00e1gina de c\u00f3digos ANSI", "Text.Utf8 = TRUE"),
  ],
  [("ToText(),STRING,PROC", "The document as plain text.", "El documento como texto plano.", "Text.LoadBlob(DOC:Body)\nDOC:PlainText = Text.ToText()"),
   ("SaveText(STRING pFileName),BYTE,PROC", "Writes it to a file.", "Lo escribe en un fichero.", "Text.SaveText('C:\\Out\\letter.txt')"),
   ("WordCount(),LONG", "The number of words.", "El n\u00famero de palabras.", "?Words{PROP:Text} = Text.WordCount() & ' words'", "?Words{PROP:Text} = Text.WordCount() & ' palabras'"),
   ("CharCount(BYTE pWithSpaces=1),LONG", "The number of characters, with or without spaces.", "El n\u00famero de caracteres, con o sin espacios.",
    "IF Text.CharCount(FALSE) > 1600 THEN MESSAGE('Too long').", "IF Text.CharCount(FALSE) > 1600 THEN MESSAGE('Demasiado largo')."),
   ("ParagraphCount() / PictureCount() / TableCount(),LONG", "Paragraphs with text, pictures and tables.", "P\u00e1rrafos con texto, im\u00e1genes y tablas.",
    "L:Info = Text.ParagraphCount() & '/' & Text.PictureCount() & '/' & Text.TableCount()"),
   ("Excerpt(LONG pMaxChars=200),STRING", "The start of the text on one line, cut at a word, with ...", "El principio del texto en una l\u00ednea, cortado en una palabra, con ...",
    "DOC:Summary = Text.Excerpt(120)       ! a browse column", "DOC:Resumen = Text.Excerpt(120)       ! columna de un browse"),
   ("IsRtf(STRING pText),BYTE", "TRUE when the string starts with {\\rtf.", "TRUE si la cadena empieza por {\\rtf.",
    "IF NOT Text.IsRtf(L:Imported) THEN L:Imported = Text.TextToRtf(L:Imported)."),
   ("TextToRtf(STRING pText, <STRING pFace>, REAL pPoints=0),STRING", "Plain text as an RTF document: escapes \\ { }, turns line breaks into paragraphs and accents into \\'e9.",
    "Texto plano como documento RTF: escapa \\ { }, convierte los saltos en p\u00e1rrafos y los acentos en \\'e9.",
    "Doc1.LoadString(Text.TextToRtf(NOTE:Memo, 'Georgia', 12))"),
  ]),
 ("rtfhtml", "RtfHtmlClass",
  ("RTF to HTML.", "RTF a HTML."),
  [("FullPage", "BYTE(1)", "a complete page; 0 = a &lt;div&gt; fragment", "una p\u00e1gina completa; 0 = un fragmento &lt;div&gt;", "Html.FullPage = FALSE"),
   ("Title", "CSTRING(256)", "the page's &lt;title&gt;", "el &lt;title&gt; de la p\u00e1gina", "Html.Title = DOC:Title"),
   ("SkipPictures", "BYTE", "leave pictures out", "deja fuera las im\u00e1genes", "Html.SkipPictures = TRUE"),
   ("ImageFolder", "CSTRING(261)", "'' = pictures embedded as data: URIs; a folder = written there as image1.png...", "'' = im\u00e1genes incrustadas como data: URI; una carpeta = se escriben ah\u00ed como image1.png...", "Html.ImageFolder = 'C:\\Site\\img'"),
   ("ImageUrl", "CSTRING(261)", "how the page links those files", "c\u00f3mo enlaza la p\u00e1gina esos ficheros", "Html.ImageUrl = 'img/'"),
  ],
  [("ToHtml(),STRING,PROC", "The document as UTF-8 HTML.", "El documento como HTML UTF-8.",
    "Html.LoadBlob(DOC:Body)\nHtml.FullPage = FALSE\nL:Body = Html.ToHtml()                ! the body of an e-mail",
    "Html.LoadBlob(DOC:Body)\nHtml.FullPage = FALSE\nL:Body = Html.ToHtml()                ! el cuerpo de un correo"),
   ("SaveHtml(STRING pFileName),BYTE,PROC", "Writes it to a file.", "Lo escribe en un fichero.",
    "Html.Title = 'Welcome letter'\nIF Html.SaveHtml('C:\\Out\\welcome.html') THEN RUN('explorer C:\\Out\\welcome.html').",
    "Html.Title = 'Carta de bienvenida'\nIF Html.SaveHtml('C:\\Out\\bienvenida.html') THEN RUN('explorer C:\\Out\\bienvenida.html')."),
  ]),
 ("rtfmd", "RtfMarkdownClass",
  ("RTF to Markdown.", "RTF a Markdown."),
  [("SkipPictures", "BYTE", "leave pictures out", "deja fuera las im\u00e1genes", "Md.SkipPictures = TRUE"),
   ("ImageFolder", "CSTRING(261)", "as RtfHtmlClass", "como en RtfHtmlClass", "Md.ImageFolder = 'C:\\Wiki\\media'"),
   ("ImageUrl", "CSTRING(261)", "as RtfHtmlClass", "como en RtfHtmlClass", "Md.ImageUrl = 'media/'"),
  ],
  [("ToMarkdown(),STRING,PROC", "The document as UTF-8 Markdown.", "El documento como Markdown UTF-8.", "Md.LoadBlob(DOC:Body)\nL:Markdown = Md.ToMarkdown()"),
   ("SaveMarkdown(STRING pFileName),BYTE,PROC", "Writes it to a file.", "Lo escribe en un fichero.", "Md.SaveMarkdown('C:\\Wiki\\' & CLIP(DOC:Code) & '.md')"),
  ]),
 ("rtfmerge", "RtfMergeClass",
  ("Mail merge: [[Name]] placeholders.", "Combinaci\u00f3n de correspondencia: marcadores [[Nombre]]."),
  [("FieldOpen", "CSTRING(9)", "the opening marker; '' = [[", "el marcador de apertura; '' = [[", "Merge.FieldOpen = '<<<<'"),
   ("FieldClose", "CSTRING(9)", "the closing marker; '' = ]]", "el marcador de cierre; '' = ]]", "Merge.FieldClose = '>>'"),
   ("UseBound", "BYTE(1)", "a field not set with SetField is looked up with EVALUATE, so BIND()ed fields fill themselves", "un campo no asignado con SetField se busca con EVALUATE, as\u00ed los campos con BIND() se rellenan solos", "Merge.UseBound = FALSE"),
   ("BlankUnknown", "BYTE", "a placeholder nothing filled becomes ''", "un marcador que nadie rellen\u00f3 queda vac\u00edo", "Merge.BlankUnknown = TRUE"),
  ],
  [("SetField(STRING pName, STRING pValue)", "A value for [[pName]]. Not case-sensitive; setting it again replaces it.", "Un valor para [[pName]]. No distingue may\u00fasculas; asignarlo otra vez lo sustituye.",
    "Merge.SetField('When', FORMAT(ORD:ShipDate, @D17))\nMerge.SetField('Total', LEFT(FORMAT(ORD:Total, @N$13.2)))",
    "Merge.SetField('Fecha', FORMAT(PED:FechaEnvio, @D17))\nMerge.SetField('Total', LEFT(FORMAT(PED:Total, @N13.2)))"),
   ("ClearFields()", "Forgets every SetField value.", "Olvida todos los valores de SetField.", "Merge.ClearFields()"),
   ("Merge(),LONG,PROC", "Fills the placeholders; returns how many were replaced. Each value takes its placeholder's formatting; one Undo takes the whole merge back.",
    "Rellena los marcadores; devuelve cu\u00e1ntos se reemplazaron. Cada valor toma el formato de su marcador; un Deshacer recupera toda la combinaci\u00f3n.",
    "Merge.LoadBlob(TPL:Body)\nBIND(CUS:Record)\nMerge.Merge()\nMerge.SaveBlob(LET:Body)"),
   ("FieldCount(),LONG / FieldName(LONG pN),STRING", "The distinct placeholders in the document.", "Los marcadores distintos del documento.",
    "LOOP I# = 1 TO Merge.FieldCount()\n  FieldQ:Name = Merge.FieldName(I#)\n  ADD(FieldQ)\nEND"),
   ("Missing(),STRING", "The placeholders nothing will fill, comma-separated.", "Los marcadores que nada rellenar\u00e1, separados por comas.",
    "IF Merge.Missing() <> '' THEN MESSAGE('No value for: ' & Merge.Missing()); RETURN.",
    "IF Merge.Missing() <> '' THEN MESSAGE('Sin valor para: ' & Merge.Missing()); RETURN."),
  ]),
]
